# Generated by Django 3.2.8 on 2022-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
